version: "3.8"

services:
  mysql:
    image: 'mysql:latest'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: 'lingoder:1.0'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
